### ISSUE TITLE
Error on direct installation in IRIS for Windows (x86-64) 2022.1 version zpm 0.3.4

### ISSUE THREAD

**Issue by SergeyMi37** [grongierisc/iris-readonly-interop#1]
install readonly-interoperability -v
 
Module readonly-interoperability was downloaded from registry (https://pm.community.intersystems.com)
Loading from C:\InterSystems\IRIS22\mgr\.modules\READONLY-INTEROPERABILITY\readonly-interoperability\1.0.2\
 
Загрузка началась в 08/30/2022 08:48:48
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\READONLY-INTEROPERABILITY\readonly-interoperability\1.0.2\module.xml как xml
Импортированный документ: readonly-interoperability.ZPM
Загрузка успешно завершена.
 
Skipping preload - directory does not exist.
Загрузка началась в 08/30/2022 08:48:48
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\READONLY-INTEROPERABILITY\readonly-interoperability\1.0.2\module.xml как xml
Импортированный документ: readonly-interoperability.ZPM
Загрузка успешно завершена.
 
Loading readonly-interoperability in process 11052
[readonly-interoperability]     Reload START (C:\InterSystems\IRIS22\mgr\.modules\READONLY-INTEROPERABILITY\readonly-interoperability\1.0.2\)
Skipping preload - directory does not exist.
Загрузка директории началась в 08/30/2022 08:48:48 '*'
 
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\READONLY-INTEROPERABILITY\readonly-interoperability\1.0.2\src\ReadOnly\Setup.cls как udl
Загрузка успешно завершена.
 
[readonly-interoperability]     Reload SUCCESS
[readonly-interoperability]     Module object refreshed.
[readonly-interoperability]     Validate START
[readonly-interoperability]     Validate SUCCESS
[readonly-interoperability]     Compile START
Компиляция началась в 08/30/2022 08:48:48 с квалификаторами 'd-lck'
Компиляция класса: ReadOnly.Setup
Компиляция программы: ReadOnly.Setup.1
Ошибка #5002: Ошибка: <CLASS DOES NOT EXIST>removeGenerated+58^%occCompile *ReadOnly.Setup
Найдено 3 ошибок при компиляции в 2.314s.
 
[readonly-interoperability]     Compile FAILURE
ERROR! WQM item modified $tlevel, before:1 after:0 for 'S %sc=$$createprojection^%occCompile(.%p1,.%p2,.%p3)' $ze='<ZSG>%Save+9^Security.Roles.1'.

**Comment by grongierisc** [comment]
the issue may be fix in version 1.0.3.
it was an error because roles and resources change in IRIS 2022, %Ens_MessageResubmit and %Ens_SequenceManager doesnt seem to exist anymore. 

Can you confirm that the problem is solved for you ?

**Comment by SergeyMi37** [comment]
Yes, problem solved, thanks.
